### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by fukemy** [hernandazevedo/androidmp3recorder#10]
i got this error:  couldn't find "libandroidmp3recorder.so". Can u help? Thanks
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app....-OOTujgZiCaoh5LcQJr9J5Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.civix.link-OOTujgZiCaoh5LcQJr9J5Q==/lib/arm64, /data/app/......-OOTujgZiCaoh5LcQJr9J5Q==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libandroidmp3recorder.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.hernandazevedo.androidmp3recorder.AndroidLameEncoder.<clinit>(AndroidLameEncoder.java:6)
        at com.hernandazevedo.androidmp3recorder.AndroidLameEncoderBuilder.build(AndroidLameEncoderBuilder.java:149)
        at com.hernandazevedo.androidmp3recorder.MP3Recorder.initAudioRecorder(MP3Recorder.java:109)
        at com.hernandazevedo.androidmp3recorder.MP3Recorder.start(MP3Recorder.java:34)
```

**Comment by ruslan-tyshchenko** [comment]
same problem..

**Comment by fukemy** [comment]
i leave this lib, use this below
```

    //lame
    implementation 'com.hernandazevedo:androidmp3recorderlib:1.0.1'
```

**Comment by fukemy** [comment]
re-open to mark this library is no longer update
